import * as Cesium from 'cesium';
import type { Cartesian3 } from 'cesium';
import type { DrawMode } from '../types/drawTypes';
export declare function calculateDistance(cart1: Cesium.Cartographic, cart2: Cesium.Cartographic): number;
export declare function calculateTotalDistance(positions: Cartesian3[]): number;
export declare function calculatePolygonArea(positions: Cartesian3[]): number;
export declare function calculateRectangleArea(positions: Cartesian3[]): number;
export declare function getRectangleCornerPositions(start: Cartesian3, end: Cartesian3): Cartesian3[];
export declare function generateCirclePositions(center: Cesium.Cartographic, radius: number, segments?: number): Cartesian3[];
export declare function formatDistance(distance: number): string;
export declare function formatArea(area: number): string;
export declare function getMinimumPointCount(mode: DrawMode): number;
