import * as Cesium from 'cesium';
import { DrawService } from '../draw/DrawService';
import { OverlayService } from '../overlay/OverlayService';
import type { MarkDrawOptions, MarkDrawResult, MarkDrawType, MarkEditOptions, MarkExportItem, MarkServiceOptions, MarkWorkAreaKind, MarkWorkAreaType } from './markTypes';
export declare class MarkService {
    private readonly viewer;
    private readonly drawService;
    private readonly overlayService;
    private readonly pointController;
    private readonly entities;
    private readonly colors;
    private readonly toolbar;
    private readonly callbacks;
    private activeDrawContext;
    private editEnabled;
    private editState;
    private readonly continuous;
    private drawSuspendedOverlayHover;
    private drawSuspendedOverlaySelection;
    constructor(viewer: Cesium.Viewer, options?: MarkServiceOptions, drawService?: DrawService, overlayService?: OverlayService);
    startDrawing(type: MarkDrawType, options?: MarkDrawOptions): void;
    drawPoint(options?: MarkDrawOptions): void;
    drawPolyline(options?: MarkDrawOptions): void;
    drawPolygon(options?: MarkDrawOptions): void;
    drawRectangle(options?: MarkDrawOptions): void;
    drawCircle(options?: MarkDrawOptions): void;
    startWorkAreaDraw(type: MarkWorkAreaType, kind?: MarkWorkAreaKind, options?: MarkDrawOptions): void;
    stopDraw(): void;
    cancelDrawing(): void;
    clearAll(): void;
    deleteEntity(entityOrId: Cesium.Entity | string): void;
    enableEdit(options?: MarkEditOptions): void;
    disableEdit(): MarkDrawResult | null;
    startEdit(entityOrId: Cesium.Entity | string, options?: MarkEditOptions): boolean;
    stopEdit(): MarkDrawResult | null;
    setColor(type: MarkDrawType, color: string): void;
    getColor(type: MarkDrawType): string;
    getEntities(): Cesium.Entity[];
    exportData(outputCoordSystem?: 'WGS84' | 'GCJ02' | 'BD09'): MarkExportItem[];
    destroy(): void;
    private suspendOverlayInteractionsForDraw;
    private resumeOverlayInteractionsAfterDraw;
    private stripAuxiliary;
    private attachMetadata;
    private getMetadata;
    private applyStyle;
    private updateEntityGeometry;
    private syncEditHandlePositions;
    private pickPosition;
    private calculateCircleRadius;
    private circleRadiusHandlePosition;
    private getRectanglePositions;
    private positionsToRectangle;
}
