import * as Cesium from 'cesium';
import type { MeasurementLabelOffset, ResolvedMeasurementFillStyle, ResolvedMeasurementLabelStyle, ResolvedMeasurementStrokeStyle, ResolvedMeasurementVertexStyle } from './types/drawTypes';
export declare const DEFAULT_LINE_WIDTH = 2;
export declare const DEFAULT_CLAMP_TO_GROUND = true;
export declare const DEFAULT_LINE_COLOR: Cesium.Color;
export declare const DEFAULT_FILL_COLOR: Cesium.Color;
export declare const DEFAULT_CIRCLE_SEGMENTS = 64;
export declare const DEFAULT_STROKE_STYLE: ResolvedMeasurementStrokeStyle;
export declare const DEFAULT_FILL_STYLE: ResolvedMeasurementFillStyle;
export declare const DEFAULT_VERTEX_STYLE: ResolvedMeasurementVertexStyle;
export declare const DEFAULT_SEGMENT_DISTANCE_LABEL_STYLE: ResolvedMeasurementLabelStyle;
export declare const DEFAULT_TOTAL_DISTANCE_LABEL_STYLE: ResolvedMeasurementLabelStyle;
export declare const DEFAULT_PREVIEW_AREA_LABEL_STYLE: ResolvedMeasurementLabelStyle;
export declare const DEFAULT_TOTAL_AREA_LABEL_STYLE: ResolvedMeasurementLabelStyle;
export declare const DEFAULT_HINT_OFFSET: MeasurementLabelOffset;
export declare const DEFAULT_HINT_BUBBLE_STYLE: ResolvedMeasurementLabelStyle;
